#!/bin/sh

# Build for Linux AMD64
env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o pget

# Build for Windows AMD64
env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o pget.exe

echo "Build completed for both Linux and Windows AMD64"

